name: oPeras.pt Deployment Workflow

on:
  push:
    branches: [ main ]  # Adjust branch names as needed
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3

    - name: Set up Tailscale
      uses: tailscale/github-action@v3
      with:
        authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
    
    - name: Deploy to server
      if: github.event_name == 'push'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/operas
          git pull origin main
          docker compose down

          export SMTP_SERVER="${{ secrets.SMTP_SERVER }}"
          export SMTP_PORT="${{ secrets.SMTP_PORT }}"
          export SMTP_USER="${{ secrets.SMTP_USER }}"
          export SMTP_PASS="${{ secrets.SMTP_PASS }}"
          export RECIPIENT_EMAIL="${{ secrets.RECIPIENT_EMAIL }}"
          export PORT="${{ secrets.PORT }}"


          docker compose build --no-cache
          docker compose up -d
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASS: ${{ secrets.SMTP_PASS }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        PORT: ${{ secrets.PORT }}